# DS4420 Project: Predicting Gold Prices with Machine Learning Models
### By Justin Wee & Andy Lin

In [ ]:
# Import Libraries
import pandas as pd

In [6]:
gold_data = pd.read_csv('gold.csv')
gold_data.head(30)

,Date,USD,EUR,JPY,GBP,CAD,CHF,INR,CNY,TRY,SAR,IDR,AED,THB,VND,EGP,KRW,RUB,ZAR,AUD
0,1/31/78,207.8,129.2,NaN,104.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2/28/78,227.3,139.5,"44,853.10",113.3,269.5,378.8,NaN,NaN,NaN,754.1,"141,796.40",869.4,"4,582.20",NaN,NaN,"111,186.60",NaN,197,198.6
2,3/31/78,245.7,151.3,"49,213.20",122.5,293.2,410.6,NaN,NaN,NaN,822.3,"153,099.60",939.1,"4,949.50",NaN,NaN,"118,284.00",NaN,209.9,216.7
3,4/28/78,242.1,149.3,"49,989.40",118.8,284.2,407.3,NaN,NaN,NaN,810.1,"151,068.50",926.2,"4,884.50",NaN,NaN,"116,507.10",NaN,204.4,215.9
4,5/31/78,239.2,148.8,"51,707.20",115.4,274.2,410.5,NaN,NaN,NaN,817.3,"149,744.30",919.9,"4,842.60",NaN,NaN,"115,555.90",NaN,202.8,215.8
5,6/30/78,257.6,161,"56,429.30",125.2,297.7,445.4,NaN,NaN,NaN,870.7,"160,957.00",983.5,"5,208.50",NaN,NaN,"124,738.20",NaN,217.6,233
6,7/31/78,279.1,173,"61,069.30",132.1,327.4,474.5,NaN,NaN,NaN,941.3,"172,550.10","1,064.80","5,592.20",NaN,NaN,"132,563.70",NaN,235.6,251.1
7,8/31/78,294.7,178.2,"63,843.10",130.5,343,486.1,NaN,NaN,NaN,980.4,"182,837.90","1,109.80","5,881.50",NaN,NaN,"137,305.90",NaN,248.5,261.4
8,9/29/78,300.8,182,"65,530.20",134.5,352,498.5,NaN,NaN,NaN,"1,024.80","190,103.60","1,147.10","6,194.90",NaN,NaN,"148,383.20",NaN,252,266.6
9,10/31/78,355.1,212.4,"78,779.20",161.6,413,571.4,NaN,NaN,NaN,"1,189.70","221,560.70","1,343.10","7,260.90",NaN,NaN,"175,525.80",NaN,294.6,314.7
10,11/30/78,391.7,235.4,"90,002.70",182.6,459.1,637.1,NaN,NaN,NaN,"1,319.00","245,305.80","1,488.50","7,981.60",NaN,NaN,"193,444.00",NaN,323.8,350.9
11,12/29/78,392,234.8,"95,936.20",183.7,461.9,643.9,NaN,NaN,NaN,"1,315.70","244,624.90","1,465.90","7,876.60",NaN,NaN,"184,889.70",NaN,324.3,357.9
12,1/31/79,455.1,268.2,"111,042.20",207.2,540.6,739.8,NaN,NaN,NaN,"1,551.90","288,307.70","1,751.80","9,383.50",NaN,NaN,"223,444.20",NaN,382,418.8
13,2/28/79,675.3,395.1,"160,503.70",298,784.8,"1,076.10",NaN,NaN,NaN,"2,264.60","421,650.50","2,551.90","13,731.50",NaN,NaN,"323,082.00",NaN,553.1,607.6
14,3/30/79,665.3,392.5,"162,529.50",290.5,769.6,"1,091.10",NaN,NaN,NaN,"2,227.30","415,365.30","2,485.20","13,469.00",NaN,NaN,"382,813.60",NaN,541.8,602.7
15,4/30/79,553.6,343.6,"137,667.90",250.7,648.9,975.8,NaN,NaN,NaN,"1,856.40","346,958.80","2,076.60","11,287.70",NaN,NaN,"330,759.40",NaN,448.8,508
16,5/31/79,517.4,326.1,"129,014.50",233.6,613.2,907,NaN,NaN,NaN,"1,717.30","322,285.80","1,927.50","10,475.50",NaN,NaN,"297,208.70",NaN,417.4,473.3
17,6/29/79,513.8,312.8,"117,281.60",223.1,603.2,854.9,NaN,NaN,NaN,"1,689.70","317,460.10","1,892.10","10,391.10",NaN,NaN,"298,538.70",NaN,406.2,454.5
18,7/31/79,600.7,361.2,"130,957.30",257,691.9,981.3,NaN,NaN,NaN,"2,008.20","376,502.80","2,233.20","12,248.20",NaN,NaN,"359,842.50",NaN,465.7,520.7
19,8/31/79,644.3,384.8,"142,641.20",271.6,743.4,"1,038.10",NaN,NaN,NaN,"2,142.50","403,482.10","2,387.60","13,093.40",NaN,NaN,"386,803.20",NaN,493.6,556.8
20,9/28/79,627.2,382.4,"140,384.50",264.5,726.4,"1,035.00",NaN,NaN,NaN,"2,072.60","390,973.10","2,303.60","12,705.70",NaN,NaN,"380,103.40",NaN,476.4,541.2
21,10/31/79,673.6,412.4,"144,562.50",280.5,784.6,"1,104.90",NaN,NaN,NaN,"2,235.20","421,213.00","2,481.00","13,697.30",NaN,NaN,"414,638.80",NaN,507.4,575.6
22,11/30/79,661.2,414.3,"138,469.50",273.6,773.7,"1,099.60",NaN,NaN,NaN,"2,195.60","413,691.10","2,436.80","13,461.80",NaN,NaN,"410,082.60",NaN,496.9,563.7
23,12/31/79,623.5,406.1,"132,816.50",260.2,739.5,"1,078.20",NaN,NaN,NaN,"2,071.20","389,668.80","2,292.50","12,758.60",NaN,NaN,"412,966.00",NaN,468.3,534.2
24,1/31/80,594.9,398.2,"124,946.00",253.7,712.9,"1,063.30",NaN,NaN,NaN,"1,981.40","372,789.80","2,191.00","12,193.50",NaN,NaN,"395,089.30",NaN,448.8,510.1
25,2/29/80,557.4,380.4,"112,804.80",231.8,663.8,"1,015.50",NaN,NaN,NaN,"1,858.00","349,397.30","2,048.50","11,461.80",NaN,NaN,"365,942.30",NaN,417.5,472.3
26,3/31/80,499.8,364.6,"103,241.80",217.9,601.2,978.3,NaN,NaN,NaN,"1,672.70","315,075.40","1,846.20","10,326.00",NaN,NaN,"343,626.80",NaN,388,431.7
27,4/30/80,498.8,362.7,"104,319.80",223.3,594.9,960.1,NaN,NaN,NaN,"1,670.60","309,761.90","1,815.00","10,129.20",NaN,NaN,"331,019.40",NaN,394.9,429.3
28,5/30/80,495.8,371.8,"106,571.40",227.6,590.9,979.1,NaN,NaN,NaN,"1,665.10","310,657.00","1,822.50","10,220.60",NaN,NaN,"343,587.50",NaN,402.4,430.5
29,6/30/80,479.7,381.7,"106,059.30",229.8,576.6,993,NaN,NaN,NaN,"1,621.30","304,239.80","1,777.10","9,988.00",NaN,NaN,"333,923.10",NaN,402.6,421

### Data Preprocessing

In [10]:
# Filter data to 2021 and later
gold_data['Date'] = pd.to_datetime(gold_data['Date'])
gold_data = gold_data[gold_data['Date'] >= '2021-01-01']
gold_data.head(30)

# Collect only the date and USD column
gold_data = gold_data[['Date', 'USD']]
gold_data.head(5)

          Date       USD
516 2021-01-29  1,867.00
517 2021-02-26  1,808.20
518 2021-03-31  1,718.20
519 2021-04-30  1,761.70
520 2021-05-31  1,853.20

In [ ]:
# ARIMA(3,1,3) model
from statsmodels.tsa.arima.model import ARIMA
model = ARIMA(gold_data['USD'], order=(3, 1, 3))
model_fit = model.fit()
print(model_fit.summary())

# Forecast the next 6 months
forecast = model_fit.forecast(steps=6)
print(forecast)

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).